### ISSUE TITLE
Updating NFS exports does not work

### ISSUE THREAD

**Issue by adamrfox** [Isilon/isilon_sdk#38]
Tested against 8.0.1.2

Ran basic NFS export create test, just created a new export with /ifs/data like in the test example, and I get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/isi_sdk/apis/protocols_api.py", line 445, in create_nfs_export
    callback=params.get('callback'))
  File "/usr/local/lib/python2.7/site-packages/isi_sdk/api_client.py", line 322, in call_api
    response_type, auth_settings, callback)
  File "/usr/local/lib/python2.7/site-packages/isi_sdk/api_client.py", line 149, in __call_api
    post_params=post_params, body=body)
  File "/usr/local/lib/python2.7/site-packages/isi_sdk/api_client.py", line 358, in request
    body=body)
  File "/usr/local/lib/python2.7/site-packages/isi_sdk/rest.py", line 209, in POST
    body=body)
  File "/usr/local/lib/python2.7/site-packages/isi_sdk/rest.py", line 177, in request
    raise ApiException(http_resp=r)
isi_sdk.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 28 Feb 2018 17:56:24 GMT', 'Content-Length': '230', 'Content-Type': 'text/html; charset=iso-8859-1', 'Server': 'Apache/2.2.34 (FreeBSD) DAV/2 mod_ssl/2.2.34 OpenSSL/1.0.2k-fips'})
HTTP response body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /platform/2/protocols/nfs/exports was not found on this server.</p>
</body></html>

**Comment by Atomicology** [comment]
@adamrfox It looks like you are using the `isi_sdk_8_0` package for communicating with your OneFS 8.0.1.2 cluster. In this case, you should be using `isi_sdk_8_0_1`, which is updated to use PAPI v4. The OneFS 8.0.1 release replaced `/platform/2/protocols/nfs/exports` with `/platform/4/protocols/nfs/exports`.
