### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'verify_ssl' with isi-sdk-8-0==0.2.1

### ISSUE THREAD

**Issue by Lucas-C** [Isilon/isilon_sdk#58]
There is the minimal code reproducing this error:
```
>>> from isi_sdk_8_0 import ApiClient
>>> ApiClient(ISILON_API_URL)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lucas_cimon/.local/share/virtualenvs/infralib-py2/lib/python2.7/site-packages/isi_sdk_8_0/api_client.py", line 71, in __init__
    self.rest_client = rest.RESTClientObject(configuration)
  File "/home/lucas_cimon/.local/share/virtualenvs/infralib-py2/lib/python2.7/site-packages/isi_sdk_8_0/rest.py", line 68, in __init__
    if configuration.verify_ssl:
AttributeError: 'unicode' object has no attribute 'verify_ssl'
```

**Comment by Lucas-C** [comment]
Sorry, I misused the Python API. I now realize I should pass a `Configuration` object to the `ApiClient` contructor.
